CREATE TABLE IF NOT EXISTS "madoc"."rules" (
    "id" SERIAL PRIMARY KEY,
    "title" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default data
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 1 - Mission Statement', 'Madoc Men''s Hockey League was formed in 1973 for the purpose of promoting recreational hockey in the City of Brampton. The executives goal is to emphasize sportsmanship and fair play for it''s members. For the purpose of this constitution Madoc Men''s Hockey League may be referred to as " the league "');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 2 - Affiliation', 'Madoc Men''s Hockey league is affiliated with the City of Brampton''s Parks & Recreation Department and will operate under the terms and conditions of the contract and affiliation policy.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 3 - Membership', 'Membership to the league is open to any " male " resident of the City of Brampton. All members must be 21 years of age. The only exception is a existing members son wishing to join but they must be a minimum of 19 years of age. All members agree to abide by the constitution & rules as set out by the executive.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 4 - Registration', 'League Fees for 2022/2023 will be');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 5 - Refunds', 'Complete refunds will be given to a player 2 days prior to the first game of the season. After the first game, refunds will be returned on a prorated basis. The player will be charged $ 20.00 per game from the first game of the season until he notifies a member of the executive.  Refunds will be paid at $15 per game for all games not played.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 6 - Re-Entry to the League', 'Any player who has quit the league and now wishes to rejoin shall be placed at the top of the waiting list for the first available spot closest to their previous rating. If a player quits the league after he has been drafted and then wishes to return in the same season, the following procedure will take place. The returning player is placed back on his originally drafted team and the rookie is placed on the team with the vacant spot. No rookie will be bumped out of the league to allow a returning player back in. Any player who has played a minimum of 10 games in the last 3 years will re-entered as a returning player unless the executive feels that a returning players skill level has changed and needs to be re-evaluated for better team balancing.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 7 - Elections', 'Elections will be held every 2 years by the current executive. During the period of June 1st, 2016 to May 31st, 2018 inclusive there will be 3 executive positions - president, vice president & treasurer. These positions are open to any current member of the league who has played a minimum of 2 years in the league. To qualify for an executive position you must be nominated by another member of the league. If 2 or more members are nominated for a position then a vote will take place by secret ballot. The new executive assumes their duties on June 1st of the year elected. As these are elected positions, you may remain on the executive for continuous terms, but must go through the election process every 2 years.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 8 - Roles of the Executive', 'The role of the executive to is manage and administrate the business affairs of this league. The executive has complete authority to make decisions they deem necessary and take appropriate action within the guidelines of this constitution for the best interest of the league. The executive is to ensure all members comply within the Policies & Procedures as set out by the City of Brampton.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 9 - Duties of the President', 'To manage and administrate the daily business affairs of the Madoc Men''s Hockey League within the guidelines of the Constitution and Rules as set out by the executive. The President is responsible for but not limited to the following duties: 1) preside at all meetings 2) act as cosigning officer with Treasurer for all legal matters ( contracts/cheques ) 3) obtain sponsorship where possible 4) arrange and negotiate for on ice game officials 5) arrange for timekeeper 6) negotiate ice contract with City of Brampton 7) chair the discipline committee 8) observe and act as off ice official for discipline issues 9) fill player vacancies 10) assist Treasurer with collecting of league fees Should a vacancy occur during the 2 year term, the President shall have the power to fill that vacancy by either ( a ) appointment or ( b ) election');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 10 - Duties of the Vice President', 'To assist the President with the business affairs of the league as required. The Vice President will oversee weekly operations and duties in the absence of the President. The Vice President is responsible for but not limited to the following duties: 1) observe and act as off ice official for discipline issues 2) maintain player stats and standings 3) assist Treasurer with collecting of league fees 4) prepare weekly game sheets 5) assist with any fundraising 6) arrange and organize yearly awards, prizes and year end banquet');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 11 - Duties of the Treasurer', 'To assist the President with the business affairs of the league as required. The Treasurer will oversee all financial matters as pertaining to the Madoc Men''s Hockey League. The Treasurer is responsible for but not limited to the following duties: 1) maintain the leagues financial records 2) act as cosigning officer with President for all legal matters ( contracts/cheques ) 3) collect league fees 4) collect sweater deposits 5) pay all invoices or contracts 6) provide financial statements by year end ( May 31st ) 7) observe and act as off ice official for discipline issues 8) assist with any fundraising 9) assist with year end banquet');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 12 - Referees', 'Madoc Men''s Hockey League has retained Carl Friday & Associates to provide 2 on ice officials for the 2017 / 2018 hockey season between the time periods covering September 1st, 2017 to May 31st, 2018 inclusive. The league agrees to pay $ 30 per referee per game. The league is to provide with a cheque in September covering refereeing costs until the end of December and then provide another cheque in January to cover refereeing costs to year end. The executive will review on a yearly basis the agreement held between our 2 parties.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 13 - Team Rep Duties', 'Each team will elect a player to represent them for general meetings, rookie draft and for any other matters that may arise during the season. The executive would prefer each team rep have at least 2 years in the league and understand the general rules C.A.H.A and Madoc Men''s Hockey League. He would also be assisting in relaying any league information to his team. EXECUTIVE ARE NOT PERMITTED TO SERVE AS TEAM REPS');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 14 - Captains & Assistant Captain Duties', 'Each team will select a captain and 2 assistant captains. It is strongly recommended that the 3 players selected into these roles have a general understanding of the rules of C.A.H.A and Madoc Men''s Hockey League. When a discussion is required to clarify a call, only 1 of either the captain or assistant captains may approach the referees to discuss the ruling. The executives expect the captains and assistant captains to be respectful and professional when dealing with the referees and in turn expect the referees to show the same courtesy when dealing with the captains. Any other player who approaches the referees crease may be subject to 2 minute delay of game penalty.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 15 - Forfeits', 'Each team is required to have a minimum of 6 players plus a goalie or 7 players on the ice ready for the scheduled start time as set out on the league schedule. If a team can not field enough players by the scheduled start time, a 5 minute grace period will be given. Once the team has enough players to start the game it will be subject to a 2 minute delay of game penalty and the late player must serve the penalty. If a team has 7 players on the ice the game will proceed at the scheduled start time even if the goalie is in the dressing room. A team with 7 players and the goalie in the room may option to take the 5 minute grace period and then be subject to the delay of game penalty when either the goalie is ready or the grace period has expired. The team is still subject to the delay of game penalty even if the goalie is ready before the grace period has expired.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 16 - Running of the Clock', 'If in the 3rd period a team is leading by 5 or more goals than the clock will continue to run until the opposing team closes the gap to 4 goals. The only exception to this rule is if a injury occurs, broken glass or power failure then the referees can stop the clock.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 17 - Sponsors', 'Madoc Men''s Hockey League is always trying to find sponsors to help reduce the cost of operating the league. Sponsorship of a team for the 2017 / 2018 season will be $ 600.00. Any player in the league wishing to sponsor a team would pay a combined rate of $ 900.00 which would include the league fee and sponsorship. The league will supply a tax receipt upon request. We ask all players try and make a effort to support our sponsors and be sure to mention that you are from Madoc Men''s Hockey League.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 18 - Game Times & Schedule', 'Game times for the 2017 / 2018 season will be 7:00pm, 8:00pm & 9:00pm. All games will be out of Century Gardens Recreation Complex located at 340 Vodden Street. Game times and location are subject to changed with as much notice as provided by the City of Brampton. The league guarantee''s 29 games based on a 6 team schedule, 24 regular season games, 5 game playoff round robin series with the top 2 teams advancing to the Championship game and the next 2 teams advancing to the Consolation game. Regular season schedules will be posted on website 2 weeks prior to the first week of the season. Playoff schedule will be posted on the bulletin board the last week of playoffs.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 19 - Warm Ups, Period Length & Penalty Carryovers', 'Here are the time guidelines for the 2017 / 2018 season Warm ups - 2minutes Period 1 - 10 minutes - 30 seconds - clock runs until first whistle after puck drop Period 2 - 10 minutes - 30 seconds - clock runs until first whistle after puck drop Period 3 - 14 minutes If a penalty occurs in the last 2 minutes of either the 1st or 2nd period the following timelines will apply ; Penalty - 2 minutes - 30 seconds - clock runs until first whistle after puck drop');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 20 - Returning Player Draft', 'Madoc Men''s Hockey League in trying to emphasize sportsmanship, fair play and create the most possible level playing field for its members.  The executive selects each years teams by a draft process held by the executive during the off season. All returning players are evaluated and rated by each member of the executive during a meeting and final ratings are agreed upon. The executive makes every effort to ensure all categories are properly balanced and every team has a chance to obtain equal number of the same rated players. If multiple vacancies occur than no team shall receive a second vacant spot on there team until every team has 1 vacant spot. If there is a father and son playing in the league and they wish to play together than the executive has the power to place the second family member on the first family members drafted team. This rule does not apply to brothers wishing to play on the same team or new players to the league for team balancing reasons. The league does rate goalies. The following categories will be used ; Forwards - A1, A2, A3 - B1, B2, B3 - C1, C2, C3 Defence - A1, A2 - B1, B2 - C1, C2');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 21 - New Player Draft', 'If league has 6 or more new players joining at the start of a season then the executive will conduct a " rookie draft " to help balance the teams. The number of games the rookies will play before the draft will be determined by the executive based on the number of rookies to ensure each team rep has a equal opportunity to evaluate the players. The executive will also rate all new players and provide a list of their " opinions " at draft night to help ensure teams properly fill their vacant spots. The order in which players are selected is based on position then from the team missing the highest rated player to the team with the lowest rated vacant spot. If 2 or more teams are missing the same level rated player the order of pick will be determined by team names drawn from hat with the team coming first out of hat getting the higher pick.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 22 - Regular Season Standings Tie Breakers', 'If a tie occurs in the standings at season end the following rules will apply ; 2 Teams Tied ; 1) most wins in regular season 2) fewest loses in regular season 3) fewest goals against in regular season 4) most wins in head to head games 5) fewest goals against in head to head games 6) fewest penalty minutes in regular season 7) fewest penalty minutes in head to head games 3 or More Teams tied ; 1) most wins in regular season 2) fewest loses in regular season 3) fewest goals against in regular season 4) fewest penalty minutes in regular season 5) most goals for in regular season');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 23 - Playoff Standings Tie Breakers', 'If a tie occurs in the standings after round robin games the following rules will apply ; 2 Teams Tied ; 1) most wins in round robin 2) winner of head to head game 3) fewest loses in round robin 4) fewest goals against 5) fewest goals against in head to head game 6) fewest penalty minutes in head to head game 7) fewest penalty minutes in round robin games 3 or More Teams Tied ; 1) most wins in round robin 2) fewest loses in round robin 3) fewest goals against in round robin 4) fewest penalty minutes in round robin games 5) most goals for in round robin');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 24 - Playoff Game Ties', 'During the round robin portion of the playoffs all ties between teams will stand. In the event of a tie in either the Championship or Consolation game the following rules will be followed. 1) 10 minute sudden death overtime 2) shootout - 3 players each - if no winner continue shootout sudden death style 3) no player may shoot twice until every player has gone once - goalies are not included 4) visiting team must shoot first');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 25 - Team Prizes & Individual Awards', 'The Madoc Men''s Hockey league supplies team prizes for the top 4 finishing teams during the playoffs as well as the regular season winners. The prizes chosen by the executive are based on the discretion and available finances of the league. If monetary prizes are awarded, the predetermined value will be subtracted from the following years league fee total.  Prize money can NOT be used as deposit, has no CASH value and may not be given to another player if you leave the league or join the executive. The Madoc Men''s Hockey League supplies individual awards to players for the following categories; 1) Most Valuable Player - league vote 2) Scoring Champ - player ( s ) obtain highest point total at end of regular season 3) Top Defenceman - league vote 4) Rookie of the Year - league vote 5) Top Goalie - league vote To qualify for individual awards both players and goalies must play a minimum of 16 regular season games.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 26 - Player Substitutions', 'If in the event a player is injured or for personal reasons going to declare himself unfit to play for a minimum of 3 games, that the league will try and fill the spot with someone from the waiting list providing there are players available on the waiting list. Substitute players will be only assigned through the President or his designate. No substitutions will be permitted during playoffs with the exception of goalies. All substitutes will pay $ 20.00 per game - $ 10.00 to missing player & $ 10.00 to the league');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 27 - Protests', 'If in the event of a protest it will be dealt with at time of incident where possible.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 28 - Rule Changes', 'If any member of the league has a suggestion to implement, delete or modify any part of the Constitution & Rules of the Madoc Men''s hockey League then they must submit the request in writing to any member of the executive for review and consideration.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 29 - C.A.H.A Rules & M.M.H.L Additional Rules', 'Madoc Men''s Hockey League is governed by the Canadian Adult Hockey Association ( C.A.H.A ) The additional rules of Madoc Men''s Hockey League will supersede the rules C.A.H.A where applicable.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 30 - Excess Of Alcohol Or Drugs', 'Any player who is assumed to have consumed and excess of alcohol or drugs will not be permitted on the ice for the safety of himself, other players and officials. The referee through the team captain or team rep will ask the player of question to leave the ice voluntarily. If the player refuses they will be assessed a game misconduct. All situations will be reviewed by the executive and will be subject to possible further disciplinary action');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 31 - Helmets & Goalie Masks', 'All players must wear a CSA approved helmet with the chin strap properly fastened. Should a players helmet come off during the play he must replace his helmet immediately or go directly to the bench. If the player makes any attempt to participate in the play without a helmet he will be assessed a 2 minute penalty. If a goalie loses his helmet at any time the play will be stopped immediately.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 32 - Minor Penalties', 'Any player receiving 3 minor penalties in a game will be ejected from the remainder of that game only. A player from the ice at the time of the third penalty must serve the penalty. Any goalie who receives 3 minor penalties in a game will remain in the game but will be suspended for the next game');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 33 - High Sticking', 'Any player who make contact with the puck above his shoulders the following rules shall apply ; If a defending player makes contact with the puck with a high stick, the play is blown dead and the faceoff will take place at the closet dot to the infraction If a offensive player makes contact with the puck with a high stick, the play is blown dead and the faceoff will take place at the closet dot to the infraction outside the blue line of the attacking team');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 34 - Body Contact', 'Madoc Men''s Hockey League is a NON CONTACT league, any body contact or unnecessary rough play will result in a 2 or 5 minute penalty at the referee''s discretion.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 35 - Game Ejection', 'Any player who receives a game ejection will be ejected from that game only. This rule is meant as a way to remove someone from that game only. Any goalie receiving a game ejection will remain in the game but will be suspended for the next game. Any player who receive 3 game ejections in a season will receive 1 game suspension A player who receives his 4th game ejection in a season will receive a 2 game suspension A player who receives his 5th game ejection in a season will receive a 4 game suspension & disciplinary meeting with executive A player who receives his 6th game ejection in a season with be suspended for a minimum 8 games & possible suspension from league');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 36 - Game Misconduct', 'Any player who receives a game misconduct will be ejected from that game and serve a further 1 game suspension Any goalie who receives a game misconduct will remain in the game and serve a further 2 game suspension. Any player or goalie who receives a game misconduct in the last 5 minutes of the 3rd period will be subject to possible further disciplinary action. All game misconducts will be reviewed by the executive and are subject to further disciplinary action.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 37 - Major Penalty', 'Any player who receives a major penalty in either the 1st or 2nd period will be ejected for the remainder of that game only. Any player who receives a major penalty in the 3rd period will be ejected for the remainder of that game and receive a further 1 game suspension. Any goalie who receives a major penalty in the 1st or 2nd period will remain in the game and be suspended for 2 additional games Any goalie who receives a major penalty in the 3rd period will remain in the game and be suspended for 1 additional game. Any player or goalie who receives a major penalty in the last 5 minutes of the 3rd period will be subject to possible further disciplinary action. All game misconducts will be reviewed by the executive and are subject to further disciplinary action.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 38 - Fighting Major', 'Any player receiving a fighting major with be ejected for the remainder of that game and be suspended for a additional 2 games. Any player receiving a second or subsequent fighting major in the same season will receive no less than 2 games and will be subject for review for further suspension or possible expulsion from the league. Any goalie who receives a fighting major in either the 1st or 2nd period will be suspended for 3 games. Any goalie who receives a fighting major in the 3rd period will be suspended for 2 games. Any goalie receiving a second or subsequent fighting major in the same season will receive no less than 2 games and will be subject for review for further suspension or possible expulsion from the league. Any player or goalie who receives a fighting major penalty in the last 5 minutes of the 3rd period will be subject to possible further disciplinary action. All fighting majors will be reviewed by the executive and are subject to further disciplinary action.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 39 - Gross Misconduct', 'Any player receiving a gross misconduct will be ejected from the remainder of that game and receive a further 2 game suspension. Any goalie who receives a gross misconduct will be ejected from the remainder of that game and receive a further 2 game suspension. Any player or goalie who receives a gross misconduct in the last 5 minutes of the 3rd period will be subject to possible further disciplinary action. All gross misconducts will be reviewed by the executive and are subject to further disciplinary. action.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 40 - Match Penalty', 'Any player receiving a match penalty will be ejected from the remainder of that game and receive a further 3 game suspension. Any goalie receiving a match penalty will be ejected from the remainder of that game and receive a further 3 game suspension All match penalty''s will be reviewed by the executive and are subject to further disciplinary action.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 41 - Post Game Misconduct', 'Any player or goalie who engages in post game misconduct ( ie ) - pushing, shoving or fighting in the handshake lineup or incident off ice will receive a minimum 5 game suspension. All post game misconducts will be reviewed by the executive and are subject to further disciplinary action.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 42 - Ejected Players', 'All ejected players must go directly to their respective dressing rooms, any deviation could result in further disciplinary action.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 43 - Dressing Rooms', 'After the completion of your game, you have until the end of the 2nd period to exit the dressing room. In accordance with the City of Brampton''s Municipal Alcohol Policy, the consumption of any alcoholic beverage is strictly prohibited. In accordance with the City of Brampton''s Municipal Smoking Policy, the consumption of any Tobacco product is strictly prohibited. Any violations that are reported to the executive by the City of Brampton will automatically result in suspensions to the player or players involved. As a league, our failure to comply could result in the cancellation of our permit.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 44 - Goalie Hit in Head by Puck', '1) any puck that hits the goaltender in the mask shall be blown dead immediately, if the pucks enters the net the goal does NOT count.');
INSERT INTO "madoc"."rules" ("title", "description") VALUES ('Article 45 - Icing the Puck', 'Madoc Men''s Hockey League does not use the centre red line as part of the game, therefore the following shall determine a icing call. 1) if a player shoots the puck from between the centre red line and his blue line or crosses the centre red line into the opposing zone than no icing shall be called 2) if a player shoots the puck from between his blue line and the end of the rink occupied by his team than icing shall be called.');