CREATE TABLE IF NOT EXISTS "madoc"."players" (
    "id" SERIAL PRIMARY KEY,
    "first_name" varchar(20),
    "last_name" varchar(20),
    "email" varchar(100),
    "phone_number" varchar(15),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "madoc"."players" ("first_name", "last_name") VALUES
    --2025 Player list
    ('Josh','Felix'),
    ('Steve','Neil'),
    ('Jordan','Cronkwright'),
    ('Troy','Smith'),
    ('Brandon','Boudreau'),
    ('Josh','Neil'),
    ('William','Felix'),
    ('Mark','Blanchard'),
    ('Brian','Felix'),
    ('Shawn','Pritchett'),
    ('Justin','Colyer'),
    ('Kevin','Hughes'),
    ('Craig','Maccan'),
    ('Duncam','Meisel'),
    ('Tyler','Tombs'),
    ('Tyler','Collins'),
    ('Brendon','Landry'),
    ('Anthony','Davis'),
    ('Keegan','Murphy'),
    ('Dan','Young'),
    ('Brian','Matkowsky'),
    ('Bruce','Froude'),
    ('Andrew','Mackay'),
    ('Mike','O''Dwyer'),
    ('Mark','Baltazar'),
    ('Paul','Collins'),
    ('Josh','Anderson'),
    ('Norm','Gottwalk'),
    ('Al','Thompson'),
    ('Jarret','Woo Sam'),
    ('Trevor','Breitkreuz'),
    ('Anthony','Izzi'),
    ('Jackson','Lee'),
    ('Conner','Parkes'),
    ('Jason','Robertson'),
    ('Colin','Parkes'),
    ('Matt','Anderson'),
    ('Sean','Gedney'),
    ('Kevin','Thompson'),
    ('Mike','Salij'),
    ('Johnathan','Yarkony'),
    ('Liam','Wynne'),
    ('Shane','Nisble'),
    ('Bo','Lee'),
    ('Zack','Sammut'),
    ('Zach','Stec'),
    ('Aiden','Murphy'),
    ('Mike','Barker'),
    ('Danny','Ryan'),
    ('Mark','Gedney'),
    ('Alex','Cornes'),
    ('Chris','Lee'),
    ('Gene','Stec'),
    ('Justin','Williams'),
    ('Chad','Springer'),
    ('Michael','Sorenson'),
    ('Jared','Kotva'),
    ('Terry','Brake'),
    ('Chris','Gedney'),
    ('Matthew','Brassard'),
    ('Tristan','Nisble'),
    ('Kyle','Kokot'),
    ('Tyler','Walker'),
    ('Alex','Klimsiak'),
    ('Jarvis','Mason'),
    ('Adam','Gray'),
    ('Peter','Froude'),
    ('Trevor','Gibbons'),
    ('Chris','Sutton'),
    ('Kyle','McGregor'),
    ('Devin','Shannon'),
    ('Dave','Mancuso'),
    ('Christian','Klimsiak'),
    ('Jason','Wise'),
    ('Victor','Pecora'),
    ('Jacob','Arsenault'),
    ('Ryan','Lanno'),
    ('Aaron','Calhoun'),
    ('Liam','Monahan'),
    ('Jeff','Hales'),
    ('Tom','Arnott'),
    ('Jake','Companion'),
    ('Jonathon','Sutton'),
    ('Darren','Davis'),
    ('Ray','Buchan'),
    ('Dawson','Fascia'),
    ('Chris','Toal'),
    ('Frank','Fascia'),
    ('Mike','Weiss');